language: go

go:
 - 1.3.3
 - tip

matrix:
  fast_finish: true

env:
  global:
    secure: UVuNPF1IgUihTLcLQDIyawnKWyWg8lNwaaceDJGy3kCtx2X1qMPy+M3Zqs4c9Id9V0vXx1wAsDxPDo6saNYVHDMQvb3yS8OIXl22ckyIWbz8BNytBdh4RrvIe0p2RVcLnBJjE5jlCPQeFf/ewkhTNvUBsNZ333MUYZWqI/fntUM=

install:
 - export GOBIN=$HOME/bin PATH=$HOM/bin:$PATH
 - go get code.google.com/p/go.tools/cmd/vet code.google.com/p/go.tools/cmd/cover github.com/mattn/goveralls github.com/modocache/gover
 - go get -t -v -u ./...
 - go install -a -race std

script:
 - go tool vet -all .
 - go build ./...
 - go test -race -v ./...
 - go list -f '{{if len .TestGoFiles}}go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}{{end}}' ./... | xargs -i sh -c {}
 - gover
 - goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
